### ISSUE TITLE
Modules Networks et sockets

### ISSUE THREAD

**Issue by ltabis** [simonmeyerrr/api#3]
Est-ce que les modules Networks génèrent eu même les sockets, ou est-ce que c'est le core (le serveur) qui leur envoit les sockets au fur et à mesure ?

**Comment by simonmeyerrr** [comment]
C'est les modules Network qui génèrent les sockets. Des commentaires sur l'interface ISocket arrivent pour expliquer le fonctionnement attendu de chaque fonction.

Le Core ne peut que:
- load la config
- load les modules grâce à la config
- dire au network de se lancer ou de s'arrêter
- update la config
