### ISSUE TITLE
Getters pour les headers des messages

### ISSUE THREAD

**Issue by Armillus** [simonmeyerrr/api#4]
Bonjour, est-ce normal qu'il n'y ait pas de getter pour les headers dans l'interface IMessage ?
Car en l'état, on ne peut pas modifier les headers des réponses, par exemple.

**Comment by simonmeyerrr** [comment]
Je pense que tu voulais dire Setter. En effet il n'y en a pas car c'est une map qui peut être remplie au fur est à mesure donc pour éviter de supprimer des données accidentellement il y a un getter de référence et il est donc possible de modifier cette référence pour modifier les headers dans IMessage.

**Comment by Armillus** [comment]
Effectivement, je voulais parler des setters.
Merci pour la réponse.
