### ISSUE TITLE
Traitement des requêtes / réponses

### ISSUE THREAD

**Issue by Armillus** [simonmeyerrr/api#5]
Bonjour,

Comment se déroule la récupération des requêtes et l'envoi des réponses dans votre API?
Il est précisé dans votre README que chaque module peut envoyer et recevoir des paquets, mais cela signifie-t-il qu'un premier module doit recevoir la requête et s'occuper de la parser ?

Si c'est le cas, pourquoi l'interface IRequest ne propose-t-elle pas de méthode pour parser un paquet reçu, afin de respecter l'encapsulation des requêtes ?

De a même manière, doit-on réaliser un module "final", qui s'occupe d'envoyer la réponse si elle n'a pas été envoyée par les précédents modules ?

Merci d'avance pour vos réponses.

**Comment by simonmeyerrr** [comment]
Bonjour,

Dans l'idée qu'on a eu il y aurait sur une configuration simple 1 module network et 3 modules http.
Le module Network possède un tableau de pointeur vers les modules http. Et lorsqu'il accepte une connexion il va lancer un thread qui va appeler chaque module http en boucle avec la structure Connection.

En boucle on aura donc:
- le module HttpReceiver: il fait des getPacket sur la requête et remplis au fur et à mesure la classe IRequest en parsant ces paquets. Une fois tous les paquets d'une requête valide reçus il va return true (pas d'erreur). Sinon si la requête est invalide il va close la socket et return false. Si la requête est incomplète il va attendre les paquets suivant.
- le module PhpCgi: il va get les informations de IRequest, faire ses petites actions et remplir la classe IResponse et return true.
- le module HttpSender: il va get les informations dans IResponse et les envoyer dans la socket avec sendPacket et return true si il n'y a aucune erreur et que la requête est en "KeepAlive". Sinon il close la socket et return false.

À la fin de cette première boucle si connexion est toujours active ça repasse dans HttpReceiver et ça jusqu'à la fermeture de la socket ou du serveur.

Selon nous c'est le travail du HttpReceiver de parser les paquets HTTP pour remplir IRequest.

**Comment by Armillus** [comment]
Bien, merci pour ces précisions.
