### ISSUE TITLE
Nom des modules.

### ISSUE THREAD

**Issue by ltabis** [simonmeyerrr/api#6]
Pour charger des modules et en décharger (notemment pour le shell), on aurait besoin du nom du module que l'on souhaite instancier/supprimer, sauf qu'aucun des trois types ne possède un tel champ. Serait il possible de rajouter un champ ```_name``` pour les classes abstraites et une method 
```std::string name() const``` dans l'interface IModule ?

**Comment by simonmeyerrr** [comment]
Okey, je push ça d'ici ce soir !

**Comment by ltabis** [comment]
Merci 👌
