### ISSUE TITLE
Certificats SSL

### ISSUE THREAD

**Issue by Armillus** [simonmeyerrr/api#7]
Bonjour,

Est-ce normal que les certificats SSL soient donnés dans la configuration du network dans le fichier config.json ?

Considérez-vous qu'il y a un module SSL ?
Si oui, cela veut dire que c'est au network de trouver ce module parmi le vecteur de modules qu'on lui donne, et de lui donner manuellement les certificats à utiliser.

Si non, cela veut-il dire que pour vous, c'est au network de gérer directement les connections sécurisées ?

Merci d'avance pour votre réponse.

**Comment by simonmeyerrr** [comment]
Pour nous c'est au network de gérer la connexion sécurisée. Il va charger les certificats au lancement du serveur depuis la config. Lorsqu'il va accepter des connexions entrantes de clients et va pouvoir initier les sockets en sécurisées et envoyer une interface ISocket aux modules http. Ce ne sera donc pas la même classe derrière ISocket que le module network de base car elles géreront de l'intérieur les read/write en securisé pour que ça n'interfère pas avec le fonctionnement des modules.

**Comment by Armillus** [comment]
D'accord, merci bien.
